version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: translation-postgres
    environment:
      POSTGRES_DB: translationdb
      POSTGRES_USER: translationuser
      POSTGRES_PASSWORD: translationpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

  translation-api:
    image: jedox-translation-tool-backend-api
    container_name: translation-api
    depends_on:
      - postgres
      - keycloak
    environment:
      # Use Docker service name 'translation-postgres' as host
      ConnectionStrings__DefaultConnection: "Host=translation-postgres;Port=5432;Database=translationdb;Username=translationuser;Password=translationpass;"
      # Optional: Keycloak config
      Keycloak__BaseUrl: "http://keycloak:8080"
      Keycloak__Realm: "Translation"
      Keycloak__ClientId: "translation-client"
      Keycloak__ClientSecret: "ZRR0g9sbKC2xtqGDTuTs5Qnn8SFFVpJN"
    ports:
      - "5294:8080"

volumes:
  pgdata:
